import React, { useState } from 'react';
import { AIInsights } from '../types';

interface AIInsightsPanelProps {
  insights: AIInsights | null;
}

const AIInsightsPanel: React.FC<AIInsightsPanelProps> = ({ insights }) => {
  const [isExpanded, setIsExpanded] = useState(true);

  if (!insights) {
    return (
      <div className="card">
        <div className="flex items-center gap-3 mb-4">
          <div className="text-2xl">🤖</div>
          <h3 className="text-xl font-bold text-gray-800">AI Insights</h3>
        </div>
        <div className="text-center py-8">
          <div className="text-4xl mb-4">⚠️</div>
          <p className="text-gray-600 mb-2">AI insights unavailable</p>
          <p className="text-sm text-gray-500">
            Gemini API may not be configured or there was an error generating insights.
          </p>
        </div>
      </div>
    );
  }

  // Format the insights text into paragraphs
  const formatInsights = (text: string) => {
    return text.split('\n\n').filter(paragraph => paragraph.trim().length > 0);
  };

  const paragraphs = formatInsights(insights.insights);

  return (
    <div className="card animate-slide-up">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-3">
          <div className="text-2xl">🤖</div>
          <h3 className="text-xl font-bold text-gray-800">AI Climate Analysis</h3>
        </div>
        <button
          onClick={() => setIsExpanded(!isExpanded)}
          className="text-gray-500 hover:text-gray-700 transition-colors"
        >
          {isExpanded ? '🔼' : '🔽'}
        </button>
      </div>

      {isExpanded && (
        <div className="space-y-4">
          <div className="bg-gradient-to-r from-blue-50 to-purple-50 p-4 rounded-lg border-l-4 border-blue-500">
            <p className="text-sm text-blue-800 font-medium mb-2">
              🧠 Powered by Gemini AI
            </p>
            <p className="text-xs text-blue-600">
              Analysis based on detected anomalies and Pakistan's historical weather records
            </p>
          </div>

          <div className="prose prose-sm max-w-none">
            {paragraphs.map((paragraph, index) => (
              <p key={index} className="text-gray-700 leading-relaxed mb-3">
                {paragraph}
              </p>
            ))}
          </div>

          <div className="mt-6 pt-4 border-t border-gray-200">
            <div className="flex items-center justify-between text-xs text-gray-500">
              <span>Generated by Gemini AI</span>
              <span>{new Date().toLocaleDateString()}</span>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AIInsightsPanel; 